// Generated by Wrangler on Mon May 27 2024 17:38:44 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	WEBHOOK_URL: string;
	DISCORD_TOKEN: string;
	DISCORD_APPLICATION_ID: string;
}
